# Generated by Django 4.1.3 on 2024-10-28 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email_contactbutton_conversion',
            old_name='campaing_name',
            new_name='title',
        ),
    ]
