# Generated by Django 4.1.3 on 2024-10-28 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_title_email_contactbutton_conversion_campaing_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
