# Generated by Django 4.2.20 on 2025-03-27 17:44

from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CRM_noticas',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='descripcion')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default='noticia.jpg', null=True, upload_to='noticias')),
            ],
        ),
        migrations.CreateModel(
            name='CRM_noticas_marketing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', django_ckeditor_5.fields.CKEditor5Field(verbose_name='descripcion')),
                ('resumen', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default='noticia.jpg', null=True, upload_to='noticias')),
                ('agente', models.CharField(max_length=50)),
                ('agente_puesto', models.CharField(max_length=50)),
                ('agente_email', models.EmailField(max_length=254)),
                ('agente_img', models.ImageField(blank=True, default='agente.jpg', null=True, upload_to='noticias')),
            ],
        ),
        migrations.CreateModel(
            name='Formulario_Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('empresa', models.CharField(max_length=60)),
                ('extension', models.IntegerField(blank=True, null=True)),
                ('intencion', models.CharField(choices=[('1', 'Explorando y deseo conocer mas sobre una posible solución'), ('2', 'Se lo que quiero y deseo apoyo de sus servicios y cotización.'), ('3', 'Necesito un equipo Demo de su solución, necesito agendarlo con ustedes.')], default='1', max_length=1)),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Hiring_Spot',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.category')),
            ],
        ),
        migrations.CreateModel(
            name='Hiring_requests',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('send_date', models.DateField(auto_now_add=True)),
                ('cv', models.FileField(upload_to='cv')),
                ('hiring_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.hiring_spot')),
            ],
        ),
    ]
