# Generated by Django 4.2.1 on 2023-07-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_noticas',
            name='descripcion',
            field=models.CharField(max_length=2500),
        ),
    ]
