# Generated by Django 4.2.1 on 2023-07-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_crm_noticas_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_noticas',
            name='titulo',
            field=models.CharField(max_length=250),
        ),
    ]
