# Generated by Django 4.2.5 on 2023-11-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_crm_noticas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_noticas',
            name='imagen',
            field=models.ImageField(blank=True, default='noticia.jpg', null=True, upload_to='noticias'),
        ),
    ]
