# Generated by Django 4.1.3 on 2024-09-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_alter_crm_noticas_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='formulario_contacto',
            name='intencion',
            field=models.CharField(choices=[('1', 'Explorando y deseo conocer mas sobre una posible solución'), ('2', 'Se lo que quiero y deseo apoyo de sus servicios y cotización.'), ('3', 'Necesito un equipo Demo de su solución, necesito agendarlo con ustedes.')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='crm_noticas',
            name='imagen',
            field=models.ImageField(blank=True, default='noticia.jpg', null=True, upload_to='noticias'),
        ),
        migrations.AlterField(
            model_name='formulario_contacto',
            name='extension',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formulario_contacto',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Hiring_Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.category')),
            ],
        ),
        migrations.CreateModel(
            name='Hiring_requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('description', models.TextField()),
                ('send_date', models.DateField(auto_now_add=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv')),
                ('hiring_spot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.hiring_spot')),
            ],
        ),
    ]
