# Generated by Django 4.1.3 on 2024-09-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_category_formulario_contacto_intencion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring_spot',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
