# Generated by Django 4.1.3 on 2024-09-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_hiring_spot_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring_requests',
            name='cv',
            field=models.FileField(default='cv.pdf', upload_to='cv'),
        ),
    ]
