# Generated by Django 4.1.3 on 2024-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_alter_hiring_requests_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring_requests',
            name='cv',
            field=models.FileField(upload_to='cv'),
        ),
        migrations.AlterField(
            model_name='hiring_requests',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
