# Generated by Django 3.2.25 on 2025-03-21 17:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_alter_category_id_alter_crm_noticas_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRM_noticas_marketing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.CharField(max_length=2500)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(blank=True, default='noticia.jpg', null=True, upload_to='noticias')),
                ('agente', models.CharField(max_length=50)),
                ('agente_puesto', models.CharField(max_length=50)),
                ('agente_email', models.EmailField(max_length=254)),
                ('agente_img', models.ImageField(blank=True, default='agente.jpg', null=True, upload_to='noticias')),
            ],
        ),
        migrations.AlterField(
            model_name='crm_noticas',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
