# Generated by Django 3.2.25 on 2025-03-21 17:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20250321_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crm_noticas_marketing',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
