# Generated by Django 3.2.25 on 2025-03-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_crm_noticas_marketing_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='crm_noticas_marketing',
            name='resumen',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
