"""
Django settings for innovative_net project.

Generated by 'django-admin startproject' using Django 2.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
keys = {}
with open(os.path.join(BASE_DIR, 'llaves.txt')) as f:
    for line in f:
        key, value = line.strip().split('=')
        keys[key] = value

SECRET_KEY = keys.get('SECRET_KEY')
# Add other keys as needed
# ANOTHER_KEY = keys.get('ANOTHER_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False  # Set to True for development, False for production

# Add this to serve static files in production
STATIC_ROOT = os.path.join(BASE_DIR, 'static/')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'staticfiles'),
]

ALLOWED_HOSTS = ['*']

# Recaptcha
RECAPTCHA_PUBLIC_KEY = keys.get('RECAPTCHA_PUBLIC_KEY')
RECAPTCHA_PRIVATE_KEY = keys.get('RECAPTCHA_PRIVATE_KEY')
RECAPTCHA_SECRET_KEY = keys.get('RECAPTCHA_SECRET_KEY')
RECAPTCHA_SITE_KEY = keys.get('RECAPTCHA_SITE_KEY')

#Monday.com
MONDAY_API_KEY = keys.get('MONDAY_API_KEY')
# Application definition

INSTALLED_APPS = [
    'homepage',
    'captcha',
    'api',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.ionos.mx'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_HOST_USER = 'no-reply@innovative-net.mx' 
EMAIL_HOST_PASSWORD = 'Sscz70ic'



ROOT_URLCONF = 'innovative_net.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'innovative_net.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Se encarga de redireccionar a la persona cuando no esta registrada
LOGIN_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
MEDIA_URL = '/media/'

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.ionos.com'  # Replace with your email provider's SMTP server
EMAIL_PORT = 465  # Replace with your email provider's SMTP port
EMAIL_HOST_USER = 'no-reply@innovative-net.mx'  # Replace with your email address
EMAIL_HOST_PASSWORD = 'Sscz70ic'  # Replace with your email password


